pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'npm install'
                sh 'npm run build'
                sh 'buildgradle clean package'
            }
        }
        stage('Docker Build'){
            steps{
                sh 'docker build -t cloud-game-frontend ./frontend'
                sh 'docker build -t cloud-game-backend ./backend'
                // sh'docker-compose build'
            }
        }
        stage('Deploy'){
            steps{
                sh 'docker-compose up -d'
            }
        }
    }
}